### ISSUE TITLE
Feature Request: Piano Roll Settings

### ISSUE THREAD

**Issue by zeta0134** [nununoisy/nsf-presenter-rs#12]
RusticNES is able to quite fully customize the piano roll rendering options, and the CLI build defaults to reading a nice big TOML file. These typically look like this:

```toml
[piano_roll]
background_color = "rgba(0, 0, 0, 255)"
canvas_height = 720
canvas_width = 1664
divider_color = "rgb(0, 0, 0)"
divider_width = 5
draw_piano_strings = true
draw_text_labels = true
key_length = 48
key_thickness = 14
octave_count = 9
scale_factor = 1
speed_multiplier = 4
starting_octave = 0
waveform_height = 96
```

In the CLI build, these are loaded and passed into the UI using the following code: <https://github.com/zeta0134/rusticnes-cli/blob/master/src/main.rs#L285>

Multiple TOML files can be loaded, and the last setting wins, so it can be rather convenient to organize global piano roll settings and then channel-specific tweaks (like color palettes) into their own files.

It would be super nice to have this option for nsf-presenter-rs, especially since the size and positioning tweaks to the keyboard can allow the rendered output to more reliably fill out the entire render resolution. This is the intended way to get rid of the large black borders at higher output sizes. (If it's already here I couldn't find the option, so this may just need documentation.) Most users will be well served by the defaults, but in my particular case, I usually like to scale the keyboard up and increase the scroll speed considerably.
